### ISSUE TITLE
[Issue] OVS Source and types are different in OSP and remotehost endpoint

### ISSUE THREAD

**Issue by pradiptapks** [perftool-incubator/tool-ovs#23]
@atheurer @k-rister @mrbojangles3 

During the `remotehost` endpoint, I noticed that ovs metrics types are different compared to `osp`(all-in-one) endpoint test scenario.

The remotehost endpoint should collect similar metrics as osp endpoint. 

**Ovs metrics types in remote host endpoint test:**
```
run-id: b704bef5-a0f0-4eb8-91aa-59a79d2b60d7
  tags: DUT=perf202.perf.lab.eng.bos.redhat.com Dpdk=20.11 Kernel=4.18.0-305.65.1.el8_4.x86_64 LACP=active OVSBOND=balance-slb OpenStack=RHOS-16.2-RHEL-8-20221111.n.1 Tgen=perf122.perf.lab.eng.bos.redhat.com Trex=v2.87 Tuned=cpu-partitioning Vnf=192.168.0.175 topo=OVN-DPDK-PVP 
  benchmark: trafficgen
  common params: active-devices=0000:06:00.0,0000:06:00.1 compress-files=ON devices=0000:06:00.0,0000:06:00.1 max-loss-pct=1 measure-latency=0 num-flows=1024 one-shot=0 process-all-profiler-data=ON rate-tolerance-failure=fail rate-unit=% rate=100 result-output=none search-runtime=30 send-teaching-measurement=ON send-teaching-warmup=ON switch-type=null teaching-measurement-packet-type=generic teaching-warmup-packet-type=generic traffic-direction=bidirectional traffic-generator=trex-txrx use-dst-ip-flows=0 use-dst-mac-flows=0 use-dst-port-flows=0 use-protocol-flows=0 use-src-ip-flows=1 use-src-mac-flows=0 use-src-port-flows=0 validation-runtime=120 warmup-trial=OFF 
  metrics:
    source: trafficgen
      types: l1-rx-bps l1-tx-bps l2-rx-bps l2-tx-bps lost-rx-pps rx-pps tx-pps trial-result 
    source: procstat
      types: interrupts-sec 
    source: mpstat
      types: Busy-CPU NonBusy-CPU 
    source: ovs-ofctl
      types: Gbps packets-sec errors-sec 
    source: sar-net
      types: L2-Gbps packets-sec 
    source: ovs-appctl
      types: upcall-flow upcall-flow-avg upcall-flow-dump-duration-ms upcall-flow-limit upcall-flow-max 
    source: sar-mem
      types: Page-faults-sec KB-Paged-in-sec KB-Paged-out-sec Pages-freed-sec 
    source: sar-scheduler
      types: Load-Average-01m Load-Average-05m Load-Average-15m Process-List-Size Run-Queue-Length 
    source: ovs-dpctl
      types: lookups-sec flows-count 
    source: sar-tasks
      types: Context-switches-sec Processes-created-sec 
    iteration-id: 6D5D1988-6D5F-11ED-BB9B-683A4B57C7BD
      unique params: frame-size=64 
      primary-period name: measurement
      samples:
        sample-id: 71251494-6D5F-11ED-ABB7-683A4B57C7BD
          primary period-id: 71AEE12E-6D5F-11ED-ABB7-683A4B57C7BD
          period range: begin: 1669446288224 end: 1669446408258
        sample-id: 703092AC-6D5F-11ED-ABB7-683A4B57C7BD
          primary period-id: 711CB8E4-6D5F-11ED-ABB7-683A4B57C7BD
          period range: begin: 1669435470468 end: 1669435590493
        sample-id: 6E222098-6D5F-11ED-88DB-683A4B57C7BD
          primary period-id: 702682D0-6D5F-11ED-ABB7-683A4B57C7BD
          period range: begin: 1669428696006 end: 1669428816031
            result: (trafficgen::rx-pps) samples: 11181370.253827 11195476.055731 11243696.705904 mean: 11206847.671821 min: 11181370.253827 max: 11243696.705904 stddev: 32682.287198 stddevpct: 0.291628
```

**Ovs metrics types in osp(all-in-one) endpoint test:**
```
run-id: ed4a2f42-2108-426e-b8b8-e8b2b25f7fb3
  tags: ComputeCount=9 Kernel=4.18.0-305.62.1.el8_4.x86_64 OpenvSwitch=2.15.6 PF=25G-Mlx-Cx5 RHOSP=RHOS-16.2-RHEL-8-20220902.n.1 SteeringMode=DMFS Test=all-in-one Time=60 vNic=Virtio-NoConntrack 
  benchmark: iperf,uperf
  common params: duration=60 ipv=4 nthreads=1 protocol=tcp time=60 
  metrics:
    source: procstat
      types: interrupts-sec 
    source: mpstat
      types: Busy-CPU NonBusy-CPU 
    source: iostat
      types: avg-req-size-kB kB-sec operations-sec avg-service-time-ms avg-queue-length operations-merged-sec percent-merged percent-utilization 
    source: ovs-dpctl
      types: ufid-Gbps ufid-packets-sec ct-stats-show lookups-sec masks-sec flows-count ufid-expired-flows-sec ufid-new-flows-sec 
    source: sar-net
      types: errors-sec L2-Gbps packets-sec 
    source: sar-mem
      types: Page-faults-sec KB-Paged-out-sec Pages-freed-sec KB-Paged-in-sec reclaimed-pages-sec Pages-swapped-out-sec VM-Efficiency Pages-swapped-in-sec kswapd-scanned-pages-sec scanned-pages-sec 
    source: sar-scheduler
      types: Load-Average-01m Load-Average-05m Load-Average-15m Process-List-Size Run-Queue-Length IO-Blocked-Tasks 
    source: ovs-ofctl
      types: Gbps packets-sec errors-sec 
    source: uperf
      types: Gbps connections-sec round-trip-usec 
    source: sar-tasks
      types: Context-switches-sec Processes-created-sec 
    source: iperf
      types: rx-Gbps rx-lost/sec rx-pps tx-Gbps 
    source: ovs-appctl
      types: upcall-flow upcall-flow-avg upcall-flow-dump-duration-ms upcall-flow-limit upcall-flow-max 
    iteration-id: 4FBD7C34-7213-11ED-ABAB-EB66066C34E1
```
